name: Android CI

# on:
#   schedule:
#     # JST: 15:05
#     - cron: '5 6 * * *'
on: [workflow_dispatch]
jobs:
        
  build:
    name: Build Apk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: bash ./gradlew assembleDebug --stacktrace
    
      - name: Upload app APK
        uses: actions/upload-artifact@v1
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
  firebase:
    name: Run Test on Firebase Test Lab
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download APK
        uses: actions/download-artifact@v1
        with:
          name: app-debug

      - id: "auth"
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
          
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: 'Use gcloud CLI'
        run: gcloud projects list

      - name: Run Test on Firebase Test Lab
        run: |
          gcloud firebase test android run \
            --type robo \
            --app app-debug/app-debug.apk \
            --device model=redfin,version=30,locale=ja,orientation=portrait \
            --robo-directives text:username=test,text:password=ppp,ignore:buttonA=,ignore:buttonB=
        
