name: Android CI2

# on:
#   schedule:
#     # JST: 15:30
#     - cron: '30 6 * * *'
on: [workflow_dispatch, push]
env:
  GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
  GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleDebug

    - name: Install Firebase CLI
      run: |
        yarn global add firebase-tools
    - name: make GOOGLE_APPLICATION_CREDENTIALS
      run: echo $GCLOUD_SERVICE_KEY | base64 -d > $GOOGLE_APPLICATION_CREDENTIALS
    - name: Distribute apk
      run: |
        firebase appdistribution:distribute \
          ./app/build/outputs/apk/debug/app-debug.apk \
          --project $PROJECT_ID \
          --app $APP_ID \
          --groups "test_app"