name: Create release note
#########
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set version
        id: version
        run: |
          REPOSITORY=$(echo ${{ github.repository }} | sed -e "s#.*/##")
          VERSION=$(echo ${{ github.ref }} | sed -e "s#refs/tags/##g")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "filename=$REPOSITORY-$VERSION" >> $GITHUB_OUTPUT
          echo "Version $VERSION"
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0

      # 現在と前回のリリース時のタグ情報の取得
      - name: Get tag ver
        id: get_tag_ver
        run: |
          echo "$(git tag --sort=creatordate | tail -n 1)" > RELEASE_TAG
          echo "release_tag=$(cat RELEASE_TAG)" >> $GITHUB_OUTPUT
          echo "$(git tag --sort=creatordate | tail -n 2 | head -n1)" > PRE_TAG
          echo "pre_tag=$(cat PRE_TAG)" >> $GITHUB_OUTPUT
      # 前回リリースからの差分をもとに、リリースノートの本文を生成する
      - name: Generate release note
        id: release_note
        run: |
          echo "release_note=$(curl -X POST -H 'Accept: application/vnd.github.v3+json' -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/repos/${{ github.repository }}/releases/generate-notes -d '{"tag_name":"${{ steps.get_tag_ver.outputs.release_tag }}", "previous_tag_name":"${{ steps.get_tag_ver.outputs.pre_tag }}"}' | jq .body | sed 's/"//g')" >> $GITHUB_OUTPUT
      # リリースノートを作成する
      - name: Create Release
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d "{ \"tag_name\": \"${{ steps.get_tag_ver.outputs.release_tag }}\", \"name\": \"${{ steps.get_tag_ver.outputs.release_tag }}\", \"body\": \"${{ steps.release_note.outputs.release_note }}\"}" \
            https://api.github.com/repos/${{ github.repository }}/releases